import libs

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt



read dataset

In [3]:
Data = pd.read_csv('bp1.csv')
Data

RowNumber  CustomerId    Surname  ...  IsActiveMember EstimatedSalary Exited
0             1    15634602   Hargrave  ...               1       101348.88      1
1             2    15647311       Hill  ...               1       112542.58      0
2             3    15619304       Onio  ...               0       113931.57      1
3             4    15701354       Boni  ...               0        93826.63      0
4             5    15737888   Mitchell  ...               1        79084.10      0
...         ...         ...        ...  ...             ...             ...    ...
9995       9996    15606229   Obijiaku  ...               0        96270.64      0
9996       9997    15569892  Johnstone  ...               1       101699.77      0
9997       9998    15584532        Liu  ...               1        42085.58      1
9998       9999    15682355  Sabbatini  ...               0        92888.52      1
9999      10000    15628319     Walker  ...               0        38190.78      0

[10000 rows x 14 columns]

Check if we have null values or not.
Because the number of rows do not change, we understand that we do not have null values.

In [4]:
Data.dropna()

RowNumber  CustomerId    Surname  ...  IsActiveMember EstimatedSalary Exited
0             1    15634602   Hargrave  ...               1       101348.88      1
1             2    15647311       Hill  ...               1       112542.58      0
2             3    15619304       Onio  ...               0       113931.57      1
3             4    15701354       Boni  ...               0        93826.63      0
4             5    15737888   Mitchell  ...               1        79084.10      0
...         ...         ...        ...  ...             ...             ...    ...
9995       9996    15606229   Obijiaku  ...               0        96270.64      0
9996       9997    15569892  Johnstone  ...               1       101699.77      0
9997       9998    15584532        Liu  ...               1        42085.58      1
9998       9999    15682355  Sabbatini  ...               0        92888.52      1
9999      10000    15628319     Walker  ...               0        38190.78      0

[10000 rows x 14 columns]

Separate X and Y values.

In [5]:
X = Data.iloc[:,3:13]
Y = Data.iloc[:,13].values
X

CreditScore Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0             619    France  Female  ...          1               1        101348.88
1             608     Spain  Female  ...          0               1        112542.58
2             502    France  Female  ...          1               0        113931.57
3             699    France  Female  ...          0               0         93826.63
4             850     Spain  Female  ...          1               1         79084.10
...           ...       ...     ...  ...        ...             ...              ...
9995          771    France    Male  ...          1               0         96270.64
9996          516    France    Male  ...          1               1        101699.77
9997          709    France  Female  ...          0               1         42085.58
9998          772   Germany    Male  ...          1               0         92888.52
9999          792    France  Female  ...          1               0         38190.78

[10000 rows x 10 columns]

For Geography and Gender, we should have numbers not string, so we change it by get_dummies

In [6]:
X = pd.get_dummies(X)
X

CreditScore  Age  Tenure  ...  Geography_Spain  Gender_Female  Gender_Male
0             619   42       2  ...                0              1            0
1             608   41       1  ...                1              1            0
2             502   42       8  ...                0              1            0
3             699   39       1  ...                0              1            0
4             850   43       2  ...                1              1            0
...           ...  ...     ...  ...              ...            ...          ...
9995          771   39       5  ...                0              0            1
9996          516   35      10  ...                0              0            1
9997          709   36       7  ...                0              1            0
9998          772   42       3  ...                0              0            1
9999          792   28       4  ...                0              1            0

[10000 rows x 13 columns]

standardizing data

In [7]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X = scaler.fit_transform(X)
X

array([[-0.32622142,  0.29351742, -1.04175968, ..., -0.57380915,
         1.09598752, -1.09598752],
       [-0.44003595,  0.19816383, -1.38753759, ...,  1.74273971,
         1.09598752, -1.09598752],
       [-1.53679418,  0.29351742,  1.03290776, ..., -0.57380915,
         1.09598752, -1.09598752],
       ...,
       [ 0.60498839, -0.27860412,  0.68712986, ..., -0.57380915,
         1.09598752, -1.09598752],
       [ 1.25683526,  0.29351742, -0.69598177, ..., -0.57380915,
        -0.91241915,  0.91241915],
       [ 1.46377078, -1.04143285, -0.35020386, ..., -0.57380915,
         1.09598752, -1.09598752]])

Split train and test values

In [8]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, Y,test_size=0.20,random_state=0)
y_train

array([0, 0, 0, ..., 0, 0, 1])

model

In [9]:
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras import Sequential

model = Sequential()

model.add(Dense(input_shape = (13,), units =6, kernel_initializer="random_uniform", activation="relu"))

model.add(Dense(units =10, kernel_initializer="random_uniform", activation="relu"))

model.add(Dense(units =1, kernel_initializer="random_uniform", activation="sigmoid"))


model.compile(optimizer='adam', loss='binary_crossentropy',metrics=['accuracy'])

model.fit(X_train, y_train, batch_size=10, epochs=100)


Epoch 1/100
800/800 [==============================] - 2s 2ms/step - loss: 0.4823 - accuracy: 0.7959
Epoch 2/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4290 - accuracy: 0.7960
Epoch 3/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4241 - accuracy: 0.7964
Epoch 4/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4202 - accuracy: 0.8183
Epoch 5/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4174 - accuracy: 0.8254
Epoch 6/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4157 - accuracy: 0.8310
Epoch 7/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4131 - accuracy: 0.8313
Epoch 8/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4119 - accuracy: 0.8321
Epoch 9/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4110 - accuracy: 0.8324
Epoch 10/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4099 - accura

In [10]:
y_predict = model.predict(X_test)
y_predict = (y_predict > 0.5)
y_test, y_predict

(array([0, 1, 0, ..., 0, 0, 0]), array([[False],
        [False],
        [False],
        ...,
        [False],
        [False],
        [False]]))

In [11]:
 from sklearn.metrics import confusion_matrix

 confusion_matrix(y_test, y_predict)

array([[1544,   51],
       [ 263,  142]])

The score of our model is 84%.

In [12]:
score = (1544+142)/2000
score

0.843